### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by Amandasilvbr** [doesnotsitproperly/faepedia#3]
Hi! I have a suggestion and an indication. There is an extension called accessibility insights for web that helps to know if the site is accessible and if it can have any visual improvement. I used it to confirm a remark about the text color "NOTICE: This wiki is still very work-in-progress. Most content is either missing or inaccurate.": it would be better to use a color that gives greater contrast, because, as you you can see in the print, the low contrast can compromise the reading of people with low vision or color blindness. Can I change the color and create a pull request? Let´s talk about!

![image](https://user-images.githubusercontent.com/100382936/180489340-4196eace-b34e-4db4-b375-d9a8602f5fd2.png)

**Comment by doesnotsitproperly** [comment]
yes, of course! thank you for bringing this to my attention. although, i've never had anyone make a pull request on any of my repositories. is there anything i need to do to allow that?

**Comment by Amandasilvbr** [comment]
You're welcome! No, it is not necessary to allow the pull request, only the merge. Do you know merge? I'll leave a text to help, I'm also a beginner and this reading helped me. In the meantime, I'll do the color change and pull request! 

https://blog.mergify.com/pull-request-vs-merge-request-whats-the-difference/

If you want to ask something about, feel fre to tell me!

**Comment by Amandasilvbr** [comment]
Okay, I made the pull request! Now, if you agree with the changes, just merge. If you don't like the color, I can change it.
